[project]
org-name= "pzfreo"
version= "0.3.1"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    path = "./lib/org.eclipse.paho.client.mqttv3-1.2.1.jar"
    modules = ["mqtt"]

    [[platform.libraries]]
    path = "../java/build/libs/ballerina-mqtt.jar"
    modules = ["mqtt"]
